id: AB8B41DF7
title: 'In Praise of Mañjuśrī: The Great Treasure of Blessings'
type: translation
pechas:
- IF88F6F3D
- I720F0F0B
- I87E1C8EE
source_metadata:
  languages:
  - en
  - es
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:10:54.666836
  last_modified_at: 2023-01-04 13:10:54.666847
  collections:
  - Mipham Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  IF88F6F3D/0EF1: F341
  I720F0F0B/9952: F341
  I87E1C8EE/599B: F341
